services:
  qazaq-ai:
    container_name: ai
    build:
      context: ./ai
    image: samiribrh/qazaq-ai:latest
    ports:
      - "8080:8080"
    env_file:
        - ./ai/.env
    networks:
      - qazaq_network

  qazaq-backend:
    container_name: backend
    build:
      context: ./backend
    image: samiribrh/qazaq-backend:latest
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - qazaq_network

  qazaq-frontend:
    container_name: frontend
    build:
      context: ./frontend
    image: samiribrh/qazaq-frontend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend:/app/node_modules
    networks:
      - qazaq_network

volumes:
  backend:
  frontend:

networks:
  qazaq_network:
    driver: bridge
