services:
  ai:
    container_name: ai
    build:
      context: ./ai
    ports:
      - "8080:8080"
    env_file:
        - ./ai/.env
    networks:
      - qazaq_network

  backend:
    container_name: backend
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - qazaq_network

networks:
  qazaq_network:
    driver: bridge
