services:
  ai:
    container_name: ai
    build:
      context: ./ai
    ports:
      - "8080:8080"
    env_file:
        - ./ai/.env
    networks:
      - qazaq_network

  redis:
    container_name: redis
    image: redis:latest
    env_file:
      - ./backend/.env.development
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - qazaq_network

networks:
  qazaq_network:
    driver: bridge

volumes:
    redis_data: