services:
  ai:
    container_name: ai
    build:
      context: ./ai
    ports:
      - "8080:8080"
    env_file:
        - ./ai/.env
    networks:
      - qazaq_network

networks:
  qazaq_network:
    driver: bridge
