"""Change table name for telemetries

Revision ID: d1aaf1995742
Revises: 8ed745d861f9
Create Date: 2024-11-09 16:49:18.268273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1aaf1995742'
down_revision: Union[str, None] = '8ed745d861f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('n', sa.Float(), nullable=False),
    sa.Column('p', sa.Float(), nullable=False),
    sa.Column('k', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('soil_humidity', sa.Float(), nullable=False),
    sa.Column('air_humidity', sa.Float(), nullable=False),
    sa.Column('light_intensity', sa.Float(), nullable=False),
    sa.Column('light_duration', sa.Float(), nullable=False),
    sa.Column('co2', sa.Float(), nullable=False),
    sa.Column('o2', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetries_id'), 'telemetries', ['id'], unique=True)
    op.drop_index('ix_telemetry_id', table_name='telemetry')
    op.drop_table('telemetry')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('n', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('p', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('k', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('soil_humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('air_humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('light_intensity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('light_duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('co2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('o2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name='telemetry_device_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='telemetry_pkey')
    )
    op.create_index('ix_telemetry_id', 'telemetry', ['id'], unique=True)
    op.drop_index(op.f('ix_telemetries_id'), table_name='telemetries')
    op.drop_table('telemetries')
    # ### end Alembic commands ###
