"""Add is_assigned and pin to Device

Revision ID: e635bc8079c4
Revises: 525e92433847
Create Date: 2024-11-09 10:59:38.368489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e635bc8079c4'
down_revision: Union[str, None] = '525e92433847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_pin', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.add_column('devices', sa.Column('is_assigned', sa.Boolean(), nullable=False))
    op.alter_column('devices', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('devices', 'serial_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'serial_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('devices', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('devices', 'is_assigned')
    op.drop_column('devices', 'device_pin')
    # ### end Alembic commands ###
