"""Adding unique constraint to device and country combination

Revision ID: a536a4d057a3
Revises: d1aaf1995742
Create Date: 2024-11-10 19:42:00.224733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a536a4d057a3'
down_revision: Union[str, None] = 'd1aaf1995742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'districts', ['country_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'districts', type_='unique')
    # ### end Alembic commands ###
