name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=1.29.2
          curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Debug Docker Username
        run: echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker-compose -f docker-compose.yml build ai backend frontend
          
          docker tag ai ${{ secrets.DOCKER_USERNAME }}/ai:latest
          docker tag backend ${{ secrets.DOCKER_USERNAME }}/backend:latest
          docker tag frontend ${{ secrets.DOCKER_USERNAME }}/frontend:latest

          docker push ${{ secrets.DOCKER_USERNAME }}/ai:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest
